### ISSUE TITLE
Interesting!

### ISSUE THREAD

**Issue by paaljoachim** [Objectivco/wordpress-simple-settings#7]
Hey

I downloaded your plugin and checked out the awesome plugin demo. It looks like a good way to create a settings area for a theme or plugin. But as I am treading into unknown territory as my focus is much more on design and finding good code snippets learning how to change these into something I need. Do you have some simple of follow documentation, tutorials, links on this for getting this to work as a theme settings section or a plugin settings section? As well as how to add and use various field settings?

I am building a custom functions plugin and am looking into different ways to create a settings screen.

Have a great day!

**Comment by clifgriffin** [comment]
It would really be implemented the same way.  You would just need to add a class to your theme so that you can extend WSS and use that class instance to access your settings and handle any custom save functionality.
