### ISSUE TITLE
Issue with activating!

### ISSUE THREAD

**Issue by Costellos** [Objectivco/wordpress-simple-settings#8]
Hello, 

First let me say how awesome this plugin is, I love it. It does exactly what I needed it to do. Now i have one problem. For some reason if you activate the plugin, then deactivate it, and then reactivate it, it gives me the following error.

Call to undefined function add_setting() in xxx/wp-content\plugins\awesome-plugin\awesome-plugin.php on line 37.

This deals with the activating of the settings. Im guessing that it has something to do with the settings existing? 

If you need my code or anything else let me know.

Thank,
Steven Costello
Costello Coding

**Comment by clifgriffin** [comment]
Hi Steven,

I assume you are activating the sample plugin just to test how it works?

Clif

**Comment by Costellos** [comment]
I added a bit to the sample, but I started with the sample. Here is what my base code looks like 

http://pastebin.com/Q3HpfZgc

**Comment by clifgriffin** [comment]
That is freaky and seemingly impossible.

I've never ever seen that error, and I've used this on many many plugins. 

What's so strange is that the class can't even exist without WordPress_SimpleSettings loaded, because it's a child class. So add_setting() has to be available. 

So it ONLY happens on immediate deactivate / reactivate...never on first activate?

**Comment by Costellos** [comment]
Thats correct, on first activate it works, but its only on reactivate it gives the error, could it be a problem with my amarok-plugin-admin.php?

If you think it is I can post it

**Comment by clifgriffin** [comment]
Unlikely. What version of PHP are you running?

**Comment by Costellos** [comment]
Mixed between my localhost and dev server. But 5.5.9 on local host and 5.4 on dev server.
